---
# file: roles/docker-pull-image/tasks/main.yaml

# *****************************************************************************
# Get the latest version of the base image this container is based upon

- name: Docker pull images
  docker_pull:
    image_name: '{{ item.value.image }}'
    pull_image_tag: '{{ item.value.tag }}'
    working_image_tag: '{{ docker_image_tag }}'
  with_dict: "{{ repository_images }}"
  tags:
    - docker_pull
